---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lucianma/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R include $DEPLOYPATH
    - /bin/cp -R screenshots $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
